# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logx < Formula
  desc "Pretty-print JSON slog logs from stdin, files, or follow mode"
  homepage "https://github.com/AyoubTadlaoui/GoLogX"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AyoubTadlaoui/GoLogX/releases/download/v0.1.4/GoLogX_0.1.4_darwin_x86_64.tar.gz"
      sha256 "26a28956f446c28030591de6453a7fc065d67418fb1a4c396f2eda8472c1f883"

      define_method(:install) do
        bin.install "logx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AyoubTadlaoui/GoLogX/releases/download/v0.1.4/GoLogX_0.1.4_darwin_arm64.tar.gz"
      sha256 "2ed4ea528178c9c974ce9db90a2397dbe5d7bd94aea7d7e5e115a936a9203afe"

      define_method(:install) do
        bin.install "logx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AyoubTadlaoui/GoLogX/releases/download/v0.1.4/GoLogX_0.1.4_linux_x86_64.tar.gz"
      sha256 "7cc384016d97546e7ada19f200f3cade84793711571b7e5d678b9578c0944165"
      define_method(:install) do
        bin.install "logx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AyoubTadlaoui/GoLogX/releases/download/v0.1.4/GoLogX_0.1.4_linux_arm64.tar.gz"
      sha256 "849ac810cac7d25bfab9c1ad2f389454fd538c7e5682e8f3d67a711af812bba8"
      define_method(:install) do
        bin.install "logx"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/logx -version")
  end
end
